"""Package version — generated by ``core/scripts/sync-versions.py``.

包版本 — 由 ``core/scripts/sync-versions.py`` 生成。

Do not edit by hand — edit ``Config/Config.json`` (``Version.CoreApi``)
and re-run the sync script.  ``CORE_VERSION`` keeps the raw display
string (e.g. ``v1.2.0-Alpha``); ``CORE_VERSION_NORMALIZED`` is the
PEP 440 form used in packaging metadata.

不要手改 — 修改 ``Config/Config.json`` 的 ``Version.CoreApi`` 后重跑同步脚本。
``CORE_VERSION`` 保留原始展示字符串（如 ``v1.2.0-Alpha``）；
``CORE_VERSION_NORMALIZED`` 是打包元数据使用的 PEP 440 形式。
"""

from __future__ import annotations

#: Raw display version from ``Config/Config.json`` → ``Version.CoreApi``.
#: 原始展示版本，来自 ``Config/Config.json`` → ``Version.CoreApi``。
CORE_VERSION = 'v1.2.0-Alpha'

#: PEP 440 normalized form (used by pyproject / ``__version__``).
#: PEP 440 规范化形式（供 pyproject / ``__version__`` 使用）。
CORE_VERSION_NORMALIZED = '1.2.0a0'

__all__ = ["CORE_VERSION", "CORE_VERSION_NORMALIZED"]
