#!/usr/bin/env python3
"""One-shot version sync — ``Config/Config.json`` is the single source of truth.

版本一键同步 — ``Config/Config.json`` 是唯一事实源。

The human maintainer edits ``Version.*`` inside ``Config/Config.json``;
this script propagates the values to every static location that still
carries a copy, so the repo never drifts:

    维护者只改 ``Config/Config.json`` 里的 ``Version.*``；本脚本把值同步到
    所有仍然携带副本的静态位置，让仓库不再各自为政：

* ``core/pyproject.toml``           ``version``          ← ``Version.CoreApi`` (PEP 440)
* ``core/xijian_api/__init__.py``   ``__version__``      ← ``Version.CoreApi`` (PEP 440)
* ``core/xijian_api/_version.py``   generated module     ← ``Version.CoreApi`` (raw + PEP 440)
* ``devkit/version.py``             ``FALLBACK_VERSION`` ← ``Version.DevKit`` (raw, keeps ``v``)
* ``devkit/xijian-devkit.spec``     ``CFBundle*Version`` ← ``Version.DevKit`` (numeric part)

Not touched (deliberately):

    刻意不动的：

* ``docs/api.md`` ``api_version`` — that is the **API protocol** version,
  a compatibility contract, not the server build version.
  — 那是 **API 协议** 版本，是兼容性契约，不是服务构建版本。

``macapp/*`` is now synced too — ``macapp/project.yml``
``MARKETING_VERSION`` follows ``Version.macOSUIApp`` (numeric form).

``macapp/*`` 也已接入同步 — ``macapp/project.yml`` 的
``MARKETING_VERSION`` 跟随 ``Version.macOSUIApp``（数值形式）。

Usage
-----

.. code-block:: bash

    python core/scripts/sync-versions.py            # write changes
    python core/scripts/sync-versions.py --dry-run  # preview only
    python core/scripts/sync-versions.py --check    # CI: exit 1 when out of sync

Every target is matched by a small, explicit pattern (regex or full-file
generation).  Nothing is guessed; an unmatched target is reported as an
error instead of being silently skipped.

每个目标都用小而明确的模式（正则或整文件生成）匹配。不做猜测；
匹配不到的目标会报错而不是被静默跳过。
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

#: Repository root — ``core/scripts/sync-versions.py`` → repo root.
#: 仓库根目录 — 由脚本位置推导。
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

DEFAULT_CONFIG = REPO_ROOT / "Config" / "Config.json"

#: Default target files (resolved against the repo root).
#: 默认目标文件（相对仓库根解析）。
DEFAULT_TARGETS = {
    "core_pyproject": REPO_ROOT / "core" / "pyproject.toml",
    "core_init": REPO_ROOT / "core" / "xijian_api" / "__init__.py",
    "core_version_module": REPO_ROOT / "core" / "xijian_api" / "_version.py",
    "devkit_version_py": REPO_ROOT / "devkit" / "version.py",
    "devkit_spec": REPO_ROOT / "devkit" / "xijian-devkit.spec",
    "macapp_project_yml": REPO_ROOT / "macapp" / "project.yml",
}

#: Generated module header — keep the "generated" marker so humans know
#: not to edit it by hand.
#: 生成模块头 — 保留「generated」标记，提醒不要手改。
_VERSION_MODULE_TEMPLATE = '''"""Package version — generated by ``core/scripts/sync-versions.py``.

包版本 — 由 ``core/scripts/sync-versions.py`` 生成。

Do not edit by hand — edit ``Config/Config.json`` (``Version.CoreApi``)
and re-run the sync script.  ``CORE_VERSION`` keeps the raw display
string (e.g. ``v1.2.0-Alpha``); ``CORE_VERSION_NORMALIZED`` is the
PEP 440 form used in packaging metadata.

不要手改 — 修改 ``Config/Config.json`` 的 ``Version.CoreApi`` 后重跑同步脚本。
``CORE_VERSION`` 保留原始展示字符串（如 ``v1.2.0-Alpha``）；
``CORE_VERSION_NORMALIZED`` 是打包元数据使用的 PEP 440 形式。
"""

from __future__ import annotations

#: Raw display version from ``Config/Config.json`` → ``Version.CoreApi``.
CORE_VERSION = {raw!r}

#: PEP 440 normalized form (used by pyproject / ``__version__``).
CORE_VERSION_NORMALIZED = {normalized!r}

__all__ = ["CORE_VERSION", "CORE_VERSION_NORMALIZED"]
'''


# ---------------------------------------------------------------------------
# Version transforms
# ---------------------------------------------------------------------------


def normalize_pep440(raw: str) -> str:
    """Normalize a display version to PEP 440.

    ``v1.2.0-Alpha`` → ``1.2.0a0``; ``v1.6.2`` → ``1.6.2``;
    ``1.0.0-Beta`` → ``1.0.0b0``.  Unknown suffixes are kept verbatim
    (the script reports them so the operator can fix the source).
    """
    v = raw.strip()
    if v.startswith("v"):
        v = v[1:]
    v = v.replace("_", "-")
    lowered = v.lower()
    for tag, repl in (
        ("-alpha", "a0"),
        ("-beta", "b0"),
        ("-rc", "rc0"),
        ("-pre", "rc0"),
    ):
        lowered = lowered.replace(tag, repl)
    return lowered


def numeric_part(raw: str) -> str:
    """Return the numeric ``X.Y.Z`` head of a version (for CFBundle).

    ``v1.6.2-Alpha`` → ``1.6.2``; ``v1.6.2`` → ``1.6.2``.
    """
    m = re.match(r"[vV]?(\d+(?:\.\d+)*)", raw.strip())
    return m.group(1) if m else ""


# ---------------------------------------------------------------------------
# Per-target readers / writers
# ---------------------------------------------------------------------------


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _patch(path: Path, pattern: str, replacement: str) -> tuple[bool, str]:
    """Replace the first match of ``pattern`` in ``path``.

    Returns ``(changed, new_content)``.  Raises ``ValueError`` when the
    pattern does not match — a missing target must be reported loudly.
    """
    content = _read(path)
    new_content, count = re.subn(pattern, replacement, content, count=1, flags=re.MULTILINE)
    if count == 0:
        raise ValueError(f"pattern not found in {path}: {pattern!r}")
    return new_content != content, new_content


# -- pyproject.toml ---------------------------------------------------------


def sync_pyproject(path: Path, normalized: str) -> tuple[bool, str]:
    """Sync ``version = "..."`` in the ``[project]`` table."""
    return _patch(
        path,
        r'^(version\s*=\s*")[^"]*(")',
        lambda m: f"{m.group(1)}{normalized}{m.group(2)}",
    )


# -- core/xijian_api/__init__.py ---------------------------------------------


def sync_core_init(path: Path, normalized: str) -> tuple[bool, str]:
    """Sync ``__version__ = "..."``."""
    return _patch(
        path,
        r'^(__version__\s*=\s*")[^"]*(")',
        lambda m: f"{m.group(1)}{normalized}{m.group(2)}",
    )


# -- core/xijian_api/_version.py (generated) ---------------------------------


def sync_core_version_module(path: Path, raw: str, normalized: str) -> tuple[bool, str]:
    """Regenerate the version module wholesale."""
    content = _VERSION_MODULE_TEMPLATE.format(raw=raw, normalized=normalized)
    old = _read(path) if path.exists() else ""
    return content != old, content


# -- devkit/version.py -------------------------------------------------------


def sync_devkit_version_py(path: Path, raw: str) -> tuple[bool, str]:
    """Sync ``FALLBACK_VERSION = "..."`` (keeps the raw ``v``-prefixed form)."""
    return _patch(
        path,
        r'^(FALLBACK_VERSION\s*=\s*")[^"]*(")',
        lambda m: f"{m.group(1)}{raw}{m.group(2)}",
    )


# -- devkit/xijian-devkit.spec -----------------------------------------------


def sync_devkit_spec(path: Path, numeric: str) -> tuple[bool, str]:
    """Sync both ``CFBundleShortVersionString`` and ``CFBundleVersion``."""
    content = _read(path)
    orig = content
    content, n1 = re.subn(
        r'("CFBundleShortVersionString"\s*:\s*")[^"]*(")',
        lambda m: f"{m.group(1)}{numeric}{m.group(2)}",
        content,
        count=1,
    )
    content, n2 = re.subn(
        r'("CFBundleVersion"\s*:\s*")[^"]*(")',
        lambda m: f"{m.group(1)}{numeric}{m.group(2)}",
        content,
        count=1,
    )
    if n1 == 0 or n2 == 0:
        raise ValueError(
            f"CFBundle version fields not found in {path} (short={n1}, bundle={n2})"
        )
    return content != orig, content


# -- macapp/project.yml -------------------------------------------------------


def sync_macapp_project_yml(path: Path, numeric: str) -> tuple[bool, str]:
    """Sync ``MARKETING_VERSION: "..."`` (numeric form from ``macOSUIApp``).

    同步 ``MARKETING_VERSION: "..."``（数值形式，来自 ``macOSUIApp``）。
    """
    return _patch(
        path,
        r'^(\s*MARKETING_VERSION:\s*")[^"]*(")',
        lambda m: f"{m.group(1)}{numeric}{m.group(2)}",
    )


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

_TARGETS = (
    ("core_pyproject", "core/pyproject.toml", "sync_pyproject", "normalized"),
    ("core_init", "core/xijian_api/__init__.py", "sync_core_init", "normalized"),
    ("core_version_module", "core/xijian_api/_version.py", "sync_core_version_module", "both"),
    ("devkit_version_py", "devkit/version.py", "sync_devkit_version_py", "raw"),
    ("devkit_spec", "devkit/xijian-devkit.spec", "sync_devkit_spec", "numeric"),
    # macOSUIApp 的数值版本（与 DevKit 的 numeric 同构，但来源不同）。
    # Numeric form of macOSUIApp (same shape as DevKit's numeric, different source).
    ("macapp_project_yml", "macapp/project.yml", "sync_macapp_project_yml", "numeric"),
)


def load_versions(config_path: Path) -> dict[str, str]:
    """Load and validate the ``Version`` section of ``Config/Config.json``."""
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read {config_path}: {exc}") from exc
    versions = data.get("Version", {})
    core = versions.get("CoreApi")
    devkit = versions.get("DevKit")
    mac = versions.get("macOSUIApp")
    if not isinstance(core, str) or not core.strip():
        raise ValueError("Config/Config.json: Version.CoreApi missing or empty")
    if not isinstance(devkit, str) or not devkit.strip():
        raise ValueError("Config/Config.json: Version.DevKit missing or empty")
    if not isinstance(mac, str) or not mac.strip():
        raise ValueError("Config/Config.json: Version.macOSUIApp missing or empty")
    return {
        "CoreApi": core.strip(),
        "DevKit": devkit.strip(),
        "macOSUIApp": mac.strip(),
    }


def run_sync(config_path: Path, *, dry_run: bool, targets: dict[str, Path] | None = None) -> list[dict]:
    """Apply (or preview) the sync across all targets.

    ``targets`` overrides the default file map (used by tests to point
    at temporary files).  Returns a per-target report:
    ``{target, status, detail}`` where status is ``changed`` /
    ``unchanged`` / ``error``.

    ``targets`` 覆盖默认文件映射（测试用它指向临时文件）。
    返回按目标的报告：``{target, status, detail}``，
    status 为 ``changed`` / ``unchanged`` / ``error``。
    """
    versions = load_versions(config_path)
    core_raw = versions["CoreApi"]
    core_norm = normalize_pep440(core_raw)
    devkit_raw = versions["DevKit"]
    devkit_numeric = numeric_part(devkit_raw)
    mac_raw = versions["macOSUIApp"]
    mac_numeric = numeric_part(mac_raw)

    target_paths = dict(DEFAULT_TARGETS)
    if targets is not None:
        target_paths.update(targets)

    report: list[dict] = []
    for target_key, target_label, fn_name, value_kind in _TARGETS:
        path = target_paths[target_key]
        fn = globals()[fn_name]
        if target_key == "macapp_project_yml":
            value = mac_numeric
        else:
            value = {"raw": core_raw, "normalized": core_norm}.get(value_kind, core_raw)
            if value_kind == "numeric":
                value = devkit_numeric
            elif fn_name == "sync_devkit_version_py":
                value = devkit_raw
        if fn_name == "sync_core_version_module":
            changed, new_content = fn(path, core_raw, core_norm)
        else:
            try:
                changed, new_content = fn(path, value)
            except Exception as exc:  # noqa: BLE001 — per-target error isolation
                report.append({"target": target_label, "status": "error", "detail": f"{type(exc).__name__}: {exc}"})
                continue
        if changed and not dry_run:
            _write(path, new_content)
        if fn_name == "sync_core_version_module":
            detail = f"→ {core_raw} / {core_norm}"
        else:
            detail = f"→ {value}"
        report.append({
            "target": target_label,
            "status": "changed" if changed else "unchanged",
            "detail": detail,
        })
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="sync-versions",
        description="Sync versions from Config/Config.json to all static locations.",
    )
    parser.add_argument(
        "--config",
        default=str(DEFAULT_CONFIG),
        help="path to Config/Config.json (default: repo Config/Config.json)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="preview changes without writing",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI mode: exit 1 when any target is out of sync or errors",
    )
    args = parser.parse_args(argv)

    config_path = Path(args.config).expanduser().resolve()
    try:
        report = run_sync(config_path, dry_run=args.dry_run or args.check)
    except ValueError as exc:
        print(f"[sync-versions] fatal: {exc}", file=sys.stderr)
        return 2

    mode = "CHECK " if args.check else "DRY-RUN " if args.dry_run else ""
    errors = 0
    for entry in report:
        flag = "ok " if entry["status"] == "unchanged" else ("!! " if entry["status"] == "error" else "-> ")
        print(f"[sync-versions] {mode}{flag}{entry['target']:36s} {entry['status']:9s} {entry['detail']}")
        if entry["status"] == "error":
            errors += 1
        if args.check and entry["status"] == "changed":
            errors += 1

    if args.check:
        print(f"[sync-versions] check finished: {errors} problem(s)")
        return 1 if errors else 0
    print(f"[sync-versions] done ({len(report)} targets, {sum(1 for e in report if e['status'] == 'changed')} changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
